"""Worker logic for ChatGPT Visible Bridge."""

from __future__ import annotations

import logging
from pathlib import Path

from .adapter import Adapter, get_adapter
from .schema import Result, ResultStatus, Task, TaskStatus
from .workspace import Workspace

logger = logging.getLogger(__name__)


class Worker:
    """One-shot worker that processes a single task."""

    def __init__(self, workspace: Workspace, adapter: Adapter) -> None:
        self.workspace = workspace
        self.adapter = adapter

    def process_one(self) -> Result | None:
        """Claim one pending task, process it, and write result.

        Returns the Result if a task was processed, None if no pending tasks.
        """
        pending = self.workspace.inbox_tasks()
        if not pending:
            logger.info("No pending tasks in inbox.")
            return None

        task_file = pending[0]
        task = Task.load(task_file)

        # Move to active
        active_path = self.workspace.active_path(task.id)
        task_file.rename(active_path)
        task.status = TaskStatus.ACTIVE
        task.save(active_path)
        logger.info("Task %s claimed (inbox -> active).", task.id)

        # Process
        try:
            result = self.adapter.send(task)
        except Exception as exc:
            logger.exception("Adapter failed for task %s.", task.id)
            result = Result(
                id=task.id,
                status=ResultStatus.FAILED,
                summary=f"Worker exception: {exc}",
                adapter=self.adapter.name,
                stop_reason="worker_exception",
            )

        # Write report
        report_path = self.workspace.report_path(task.id)
        report_content = self._build_report(task, result)
        report_path.write_text(report_content, encoding="utf-8")
        result.report_path = str(report_path)

        # Write result
        result_path = self.workspace.result_path(task.id)
        result.save(result_path)

        # Move task to final status location
        if result.status == ResultStatus.SUCCESS:
            # Active task stays as completed record; we keep it in outbox for history
            # For simplicity, move the active file to outbox as completed marker
            completed_path = self.workspace.outbox / f"{task.id}_task.json"
            task.status = TaskStatus.COMPLETED
            task.save(completed_path)
            active_path.unlink()
            logger.info("Task %s completed (active -> outbox).", task.id)
        else:
            failed_path = self.workspace.failed_path(task.id)
            task.status = TaskStatus.FAILED if result.status == ResultStatus.FAILED else TaskStatus.BLOCKED
            task.save(failed_path)
            active_path.unlink()
            logger.info("Task %s failed/blocked (active -> failed).", task.id)

        return result

    def _build_report(self, task: Task, result: Result) -> str:
        lines = [
            f"# ChatGPT Visible Bridge Report",
            f"",
            f"**Task ID:** {task.id}",
            f"**Status:** {result.status.value}",
            f"**Adapter:** {result.adapter}",
            f"**Mode:** {task.mode.value}",
            f"**Created:** {task.created_at}",
            f"**Completed:** {result.completed_at}",
            f"",
            f"---",
            f"",
            f"## Original Prompt",
            f"",
            f"```text",
            f"{task.prompt}",
            f"```",
            f"",
            f"---",
            f"",
            f"## Response Summary",
            f"",
            f"{result.summary}",
            f"",
        ]

        if result.stop_reason:
            lines.extend([
                f"**Stop Reason:** {result.stop_reason}",
                f"",
            ])

        if result.suggested_next_action:
            lines.extend([
                f"## Suggested Next Action",
                f"",
                f"{result.suggested_next_action}",
                f"",
            ])

        if result.response_markdown:
            lines.extend([
                f"---",
                f"",
                f"## Response Markdown",
                f"",
                result.response_markdown,
                f"",
            ])

        lines.extend([
            f"---",
            f"",
            f"_Generated by ChatGPT Visible Bridge (adapter={result.adapter})_",
        ])

        return "\n".join(lines)


def process_one(workspace: Workspace | None = None, adapter_name: str = "mock") -> Result | None:
    """High-level helper to process one task."""
    ws = workspace or Workspace()
    ws.ensure_dirs()
    adapter = get_adapter(adapter_name)
    worker = Worker(ws, adapter)
    return worker.process_one()


def drain(workspace: Workspace | None = None, adapter_name: str = "mock") -> list[Result]:
    """High-level helper to process all pending tasks."""
    ws = workspace or Workspace()
    ws.ensure_dirs()
    adapter = get_adapter(adapter_name)
    worker = Worker(ws, adapter)
    results = []
    while True:
        result = worker.process_one()
        if result is None:
            break
        results.append(result)
    return results
